version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip s3_lambda_sns_topic_1.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://aws-sumit-gds/s3-lambda-sns/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name s3-lambda-sns-demo --s3-bucket aws-sumit-gds --s3-key deployment_package.zip
      - echo "Deployment complete!"