version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Used lambda layers for dependencies..."
  build:
    commands:
      - echo "Copying code to S3 bucket..."
      - cp s3_lambda_sns_topic_1.py lib/
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - echo "Uploading deployment package to S3 bucket..."
      - aws s3 cp deployment_package.zip s3://aws-sumit-gds/s3-lambda-sns/
      - echo "Updating Lambda function code via S3..."
      - aws lambda update-function-code --function-name s3-lambda-sns-demo --s3-bucket aws-sumit-gds --s3-key deployment_package.zip
      - echo "Deployment complete!"