version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Used lambda layers for dependencies..."
  build:
    commands:
      - echo "Copying code to S3 bucket..."
      - mkdir lambda_function
      - cp src/lambda_function.py lambda_function/
      - cd lambda_function
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - echo "Uploading deployment package to S3 bucket..."
      - aws s3 cp deployment_package.zip s3://aws-sumit-gds/airbnb-booking-records/
      - echo "Uploaded deployment package to S3 bucket..."
      - echo "Updating Lambda function code via S3..."
      - aws lambda update-function-code --function-name produce-airbnb-booking-data --s3-bucket aws-sumit-gds --s3-key airbnb-booking-records/deployment_package.zip
      - echo "Deployment complete!"